//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.utils;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class ISettings_
    extends SharedPreferencesHelper
{

    private Context context_;

    public ISettings_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_ISettings"), 0));
        this.context_ = context;
    }

    public ISettings_.ISettingsEditor_ edit() {
        return new ISettings_.ISettingsEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public IntPrefField age() {
        return intField("age", 0);
    }

    public BooleanPrefField haveBoyFriend() {
        return booleanField("haveBoyFriend", false);
    }

    public BooleanPrefField maritalStatus() {
        return booleanField("maritalStatus", false);
    }

    public StringPrefField name() {
        return stringField("name", "");
    }

    public StringPrefField surname() {
        return stringField("surname", "");
    }

    public final static class ISettingsEditor_
        extends EditorHelper<ISettings_.ISettingsEditor_>
    {


        ISettingsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public IntPrefEditorField<ISettings_.ISettingsEditor_> age() {
            return intField("age");
        }

        public BooleanPrefEditorField<ISettings_.ISettingsEditor_> haveBoyFriend() {
            return booleanField("haveBoyFriend");
        }

        public BooleanPrefEditorField<ISettings_.ISettingsEditor_> maritalStatus() {
            return booleanField("maritalStatus");
        }

        public StringPrefEditorField<ISettings_.ISettingsEditor_> name() {
            return stringField("name");
        }

        public StringPrefEditorField<ISettings_.ISettingsEditor_> surname() {
            return stringField("surname");
        }

    }

}
