//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.carcreator;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.SeekBar;
import com.example.carcreator.R.id;
import com.example.carcreator.R.layout;
import com.example.utils.ISettings_;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ACarCreator_
    extends ACarCreator
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_acar_creator);
    }

    private void init_(Bundle savedInstanceState) {
        myPrefs = new ISettings_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ACarCreator_.IntentBuilder_ intent(Context context) {
        return new ACarCreator_.IntentBuilder_(context);
    }

    public static ACarCreator_.IntentBuilder_ intent(Fragment supportFragment) {
        return new ACarCreator_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ibAdd = ((ImageButton) hasViews.findViewById(id.ibAdd));
        ivPhoto = ((ImageView) hasViews.findViewById(id.ivPhoto));
        etEngineVolume = ((EditText) hasViews.findViewById(id.etEngineVolume));
        sbProductionYear = ((SeekBar) hasViews.findViewById(id.sbProductionYear));
        etDoorsAmmount = ((EditText) hasViews.findViewById(id.etDoorsAmmount));
        etProductionYear = ((EditText) hasViews.findViewById(id.etProductionYear));
        etCarName = ((EditText) hasViews.findViewById(id.etCarName));
        ibList = ((ImageButton) hasViews.findViewById(id.ibList));
        {
            View view = hasViews.findViewById(id.ivPhoto);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ACarCreator_.this.ivPhoto();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.ibAdd);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ACarCreator_.this.ibAdd();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.ibList);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ACarCreator_.this.ibList();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  200 :
                ACarCreator_.this.onResult(data);
                break;
        }
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ACarCreator_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ACarCreator_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ACarCreator_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
